### ISSUE TITLE
No Bitches (Fatal Bug)

### ISSUE THREAD

**Issue by anoxysm** [Statsify/statsify#10]
How to reproduce: re-evaluate all of the bitches you have (which is zero)

Probable solution: go get some bitches

**Comment by ugcodrr** [comment]
Hello sir,

I am sorry to whoever disturbed you but this is not the right time or place to do this.

Have a good day (or don't).

I didn't ask + skill issue + ratio + cope + cancelled + quote tweet + you fell off
