### ISSUE TITLE
Minigame Commands (Profile/JSX , Historical)

### ISSUE THREAD

**Issue by ugcodrr** [Statsify/statsify#137]
### Which package is the feature request for?

discord-bot

### Feature

Minigame commands containing versions: 
- [x] Normal
- [x] Historical

### Ideal solution or implementation

Add commands for these Hypixel Gamemodes that have all of the previously mentioned versions.

- [x] Arcade
	- [x] Overall/Summary
	- [x] Blocking Dead
	- [x] Bounty Hunters
	- [x] Dragon Wars
	- [x] Ender Spleef
	- [x] Farm Hunt
	- [x] Football
	- [x] Galaxy Wars
	- [x] Hole In The Wall
	- [x] Hide & Seek
	- [x] Hypixel Says
	- [x] Mini Walls
	- [x] Party Games
	- [x] Pixel Painters
	- [x] Throw Out
	- [x] Zombies
- [x] Arena Brawl
	- [x] Overall
	- [x] Solo
	- [x] Doubles
	- [x] Fours
- [x] Bedwars
	- [x] Overall
	- [x] Core
	- [x] Solo
	- [x] Doubles
	- [x] Threes
	- [x] Fours
	- [x] 4v4
	- [x] Dreams
	  - [x] Castle
	  - [x] Armed
	  - [x] Lucky Block
	  - [x] Rush 
	  - [x] Ultimate 
	  - [x] Voidless 
	  - [x] Swap 
- [x] Blitz Survival Games
	- [x] Overall
	- [x] Solo
	- [x] Doubles
	- [x] Kits
	  - [x] Arachnologist
	  - [x] Archer
	  - [x] Armorer
	  - [x] Astronaut
	  - [x] Baker
	  - [x] Blaze
	  - [x] Creepertamer
	  - [x] Diver
	  - [x] Donkeytamer
	  - [x] Farmer
	  - [x] Fisherman
	  - [x] Florist
	  - [x] Golem
	  - [x] Guardian
	  - [x] Horsetamer
	  - [x] Hunter
	  - [x] Hype Train
	  - [x] Jockey
	  - [x] Knight
	  - [x] Meatmaster
	  - [x] Milkman
	  - [x] Necromancer
	  - [x] Paladin
	  - [x] Phoenix
	  - [x] Pigman
	  - [x] Rambo
	  - [x] Randon
	  - [x] Ranger
	  - [x] Reaper
	  - [x] Rogue
	  - [x] Red Dragon
	  - [x] Rogue
	  - [x] Scout
	  - [x] Shadow Knight
	  - [x] Shark
	  - [x] Slimey Slime
	  - [x] Snowman
	  - [x] Speleologist
	  - [x] Tim
	  - [x] Toxicologist
	  - [x] Troll
	  - [x] Viking
	  - [x] Warlock
	  - [x] Warrior
	  - [x] Wolftamer
- [x] Build Battle
- [x] Cops & Crims
- [x] Duels
	- [x] Overall
	- [x] Bridge
	- [x] Classic
	- [x] UHC
	- [x] Combo
	- [x] Skywars
	- [x] Sumo
	- [x] No Debuff
	- [x] Bow
	- [x] OP
	- [x] Blitz SG
	- [x] Mega Walls
	- [x] Bow Spleef
	- [x] Boxing
	- [x] Parkour
	- [x] Arena
- [x] General/Hypixel/Main
- [x] Megawalls
- [x] Murder Mystery
	- [x] Overall
	- [x] Assassins
	- [x] Classic
	- [x] Double Up
	- [x] Infection
- [x] Paintball
- [ ] Pit
	- [ ] Overall
	- [ ] Inventory
- [x] Quake
- [x] Skywars
	- [x] Overall
	- [x] Solo
	- [x] Doubles
	- [ ] Ranked
	- [x] Lab
	  - [x] TNT Madness
	  - [x] Lucky Blocks
	  - [x] Slime
	  - [x] Rush
- [x] Smash Heroes
	- [x] Overall
	- [x] Solo
	- [x] Doubles
	- [x] Teams
	- [x] Kits
	  - [x] Bulk
	  - [x] General Cluck
	  - [x] Cake Monster
	  - [x] Botmon
	  - [x] Tinman
	  - [x] Maruader
	  - [x] Spooderman
	  - [x] Pug
	  - [x] Cryomancer
	  - [x] Sgt. Shield
	  - [x] Karakot
	  - [x] Skullfire
	  - [x] Sanic
	  - [x] Void Crawler
	  - [x] Shoop
	  - [x] Green Hood 
- [x] Speed UHC
	- [x] Overall
	- [x] Solo 
	- [x] Teams
	- [x] Kits
- [x] TNT Games
	- [x] TNT Run
	- [x] PVP Run
	- [x] TNT Tag
	- [x] Bow Spleef 
	- [x] Wizard
- [x] Turbo Kart Racers
- [x] UHC
	- [x] Overall
	- [x] Solo
	- [x] Teams
- [x] VampireZ
- [x] Walls
- [x] Warlords
- [x] WoolWars

**Comment by jacobk999** [comment]
A separate issue will be made for Pit and Ranked SkyWars
