### ISSUE TITLE
Mega Walls playtime is wrong

### ISSUE THREAD

**Issue by Alexdoru** [Statsify/statsify#613]
### Which package is this bug report for?

discord-bot

### Issue description

This line https://github.com/Statsify/statsify/blob/728351716bf18b0abc49784b160a62fc97f4f200/packages/schemas/src/player/gamemodes/megawalls/kit.ts#L140 should be only `this.playtime = data.time_played * 60_000; `

Because the field time_played in the api is actually equals to time_faceoff + time_standard, so by adding time_played + time_standard you are roughlty counting the playtime twice. I fixed this bug in my mod too : https://github.com/Alexdoru/MegaWallsEnhancements/commit/8c55fd130a119d0efcf6654c02f6c49d621912d2

**Comment by ugcodrr** [comment]
Thanks for making an issue and pointing this out, appreciate it!

**Comment by Alexdoru** [comment]
Thank you!

**Comment by Alexdoru** [comment]
following this change you need to invalidate the cache of the playtime leaderboards
